### ISSUE TITLE
crash issue

### ISSUE THREAD

**Issue by akmj12345** [Freakler/CheatDeviceRemastered#11]
Already try the latest version, when i play gta vcs and doing mission, the game crashed everytime go into cutscene. and when i try with the old version, it works (the old one "Edison Carter")

**Comment by Freakler** [comment]
Since "the old version" works I assume you are using a real PSP. Since its only crashing when a cutscene starts I assume its a memory problem. Did you enable high memory layout? If its a PSP 1000, are you using the _lite.prx version? 

For further help please come join the discord! https://discord.gg/7DERFmkgYq

**Comment by akmj12345** [comment]
I'm using the 3000 series, and I already tested with a disabled "High memory layout" It is still the same, every time I enter the next objective which is a cutscene, the game crashes and blanks, the lite. prx was already deleted when I installed, it cause I know mine is 3000
